#!/bin/bash -x
sudo yum install fio -y
sudo yum install nginx -y
sudo systemctl enable nginx
sudo systemctl start nginx
sudo hostname >> /usr/share/nginx/html/index.html
sudo cat /etc/os-release >> /usr/share/nginx/html/index.html
